name: Go

on:
  push:
    branches: [ "master-branch" ]
  pull_request:
    branches: [ "master-branch" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - name: Test
      run: make test



