name: CI-test

on:
  push:
    branches: [ "master-branch" ]
  pull_request:
    branches: [ "master-branch" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the GO module directory
    - uses: actions/checkout@v3

    - name: Test
      run: make test
